FROM node:carbon

RUN mkdir -p /app
WORKDIR /app
ADD ./ /app


RUN npm install
RUN npm install pm2 -g
ENV NODE_ENV=production

EXPOSE 5000
#CMD pm2 start ./src/server.js -i max
CMD ["pm2-runtime", "ecosystem.config.js"]